project_name: oauth2-proxy
builds:
- env:
  - CGO_ENABLED=0
  binary: oauth2-proxy
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
nfpms:
  # note that this is an array of nfpm configs
  -
   vendor: Securepoint GmbH
   file_name_template: "{{ .PackageName }}_{{ .Os }}_{{ .Arch }}"
   formats:
    - deb